const shows=[
{key:'demon-slayer',title:'Demon Slayer',search:'Demon Slayer',score:'8.6',genres:['Action','Fantasy','Adventure'],desc:'Tanjiro Kamado sets out on a dangerous journey to find a cure for his sister and confront the forces behind her transformation.'},
{key:'one-piece',title:'One Piece',search:'One Piece',score:'9.0',genres:['Action','Adventure','Fantasy'],desc:'Follow Luffy and the Straw Hat crew on a huge adventure filled with friendship, freedom and the search for the legendary treasure.'},
{key:'solo-leveling',title:'Solo Leveling',search:'Solo Leveling',score:'8.8',genres:['Action','Fantasy'],desc:'Sung Jinwoo rises from the weakest hunter into a powerful fighter after gaining a mysterious system.'},
{key:'jujutsu-kaisen',title:'Jujutsu Kaisen',search:'Jujutsu Kaisen',score:'8.7',genres:['Action','Supernatural'],desc:'A supernatural action series where sorcerers battle dangerous curses and protect people from the unseen.'},
{key:'spy-family',title:'SPY x FAMILY',search:'SPY x FAMILY',score:'8.5',genres:['Comedy','Action'],desc:'A spy, an assassin and a telepath form a fake family while each secretly hides the truth from the others.'},
{key:'frieren',title:"Frieren: Beyond Journey's End",search:'Sousou no Frieren',score:'9.1',genres:['Fantasy','Adventure','Drama'],desc:'A thoughtful fantasy adventure about memories, friendship and understanding people long after the great battle is over.'},
{key:'mha',title:'My Hero Academia',search:'Boku no Hero Academia',score:'8.3',genres:['Action','Adventure'],desc:'A hero-school story about courage, rivalry, teamwork and learning what it means to become a hero.'},
{key:'aot',title:'Attack on Titan',search:'Shingeki no Kyojin',score:'9.0',genres:['Action','Drama','Adventure'],desc:'A dramatic survival story built around mystery, difficult choices and a fight for humanity’s future.'},
{key:'death-note',title:'Death Note',search:'Death Note',score:'8.6',genres:['Psychological','Thriller'],desc:'A psychological thriller centered on a supernatural notebook and the consequences of using its mysterious power.'},
{key:'fullmetal',title:'Fullmetal Alchemist: Brotherhood',search:'Fullmetal Alchemist: Brotherhood',score:'9.1',genres:['Action','Adventure','Drama'],desc:'Two brothers pursue the Philosopher’s Stone while uncovering a much larger conspiracy.'}
];
const regions={ZA:{name:'South Africa',path:'za'},US:{name:'United States',path:'us'},GB:{name:'United Kingdom',path:'uk'},CA:{name:'Canada',path:'ca'},AU:{name:'Australia',path:'au'},DE:{name:'Germany',path:'de'},JP:{name:'Japan',path:'jp'}};
let saved=JSON.parse(localStorage.getItem('otakuSaved')||'[]'), filter='All', heroIndex=0;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function tile(a){return `<article class="anime-tile" onclick="openInfo('${a.key}')"><img class="tile-img" src="${a.image||''}" alt="${esc(a.title)} poster" loading="lazy"><button class="tile-play" aria-label="Watch trailer">▶</button><div class="tile-body"><div class="tile-title">${esc(a.title)}</div><div class="tile-meta"><span class="tile-score">★ ${a.score}</span> · ${esc(a.genres[0])}</div></div></article>`}
function libraryCard(a){const isSaved=saved.includes(a.key);return `<article class="library-card"><img class="cover" src="${a.image||''}" alt="${esc(a.title)} poster" loading="lazy"><div class="body"><h3>${esc(a.title)}</h3><div class="tile-meta"><span class="tile-score">★ ${a.score}</span> · ${a.genres.join(' · ')}</div><p>${esc(a.desc)}</p><div class="tags">${a.genres.slice(0,3).map(g=>`<span class="tag">${esc(g)}</span>`).join('')}</div><div class="card-actions"><button class="small-btn primary" onclick="event.stopPropagation();openInfo('${a.key}')">▶ Trailer</button><button class="small-btn" onclick="event.stopPropagation();toggleSaved('${a.key}')">${isSaved?'✓ Saved':'＋ List'}</button></div></div></article>`}
function render(){const q=(document.querySelector('#search')?.value||'').toLowerCase();const arr=shows.filter(a=>(filter==='All'||a.genres.includes(filter))&&(a.title+' '+a.genres.join(' ')).toLowerCase().includes(q));document.querySelector('#libraryGrid').innerHTML=arr.length?arr.map(libraryCard).join(''):'<div class="empty" style="grid-column:1/-1">⌕<h3>No anime found</h3><p>Try another title or genre.</p></div>';const s=shows.filter(a=>saved.includes(a.key));document.querySelector('#savedGrid').innerHTML=s.map(libraryCard).join('');document.querySelector('#emptyList').style.display=s.length?'none':'block';}
function rows(){document.querySelector('#trendingRow').innerHTML=shows.slice(0,8).map(tile).join('');document.querySelector('#topRow').innerHTML=[...shows].sort((a,b)=>+b.score-+a.score).slice(0,8).map(tile).join('');document.querySelector('#recentRow').innerHTML=[...shows].reverse().slice(0,8).map(tile).join('')}
function toggleSaved(key){saved=saved.includes(key)?saved.filter(x=>x!==key):[...saved,key];localStorage.setItem('otakuSaved',JSON.stringify(saved));render()}
function setFilter(v){filter=v;document.querySelectorAll('.genre').forEach(x=>x.classList.toggle('active',x.dataset.filter===v));render();document.querySelector('#browse').scrollIntoView({behavior:'smooth'})}
function region(){return regions[localStorage.getItem('otakuRegion')||'ZA']}
function justwatch(a){return `https://www.justwatch.com/${region().path}/search?q=${encodeURIComponent(a.title)}`}
function serviceLinks(a){const q=encodeURIComponent(a.title);return `<a target="_blank" rel="noopener" href="https://www.crunchyroll.com/search?q=${q}">Crunchyroll ↗</a><a target="_blank" rel="noopener" href="https://www.netflix.com/search?q=${q}">Netflix ↗</a><a target="_blank" rel="noopener" href="https://www.primevideo.com/search/ref=atv_nb_sr?phrase=${q}">Prime Video ↗</a>`}
function trailer(a){if(a.trailerSite==='youtube'&&a.trailerId)return `<div class="video"><iframe src="https://www.youtube-nocookie.com/embed/${a.trailerId}?rel=0" title="${esc(a.title)} official trailer" allow="accelerometer; autoplay; encrypted-media; picture-in-picture; web-share" allowfullscreen></iframe></div>`;return `<div class="video fallback"><div><h3>Official trailer</h3><p>There isn't an embeddable trailer recorded for this title yet.</p><a class="btn primary" target="_blank" rel="noopener" href="https://www.youtube.com/results?search_query=${encodeURIComponent(a.title+' official trailer')}">Open trailer search →</a></div></div>`}
function openInfo(key){const a=shows.find(x=>x.key===key);const r=region();document.querySelector('#modalContent').innerHTML=`<div class="preview"><div><span class="featured">OFFICIAL TRAILER</span><h2>${esc(a.title)}</h2><p><b class="tile-score">★ ${a.score}/10</b> · ${a.genres.join(' · ')}</p>${trailer(a)}</div><aside class="watch-panel"><h3>Where to Watch</h3><label>Region<select class="region-select" onchange="setRegion(this.value)">${Object.entries(regions).map(([k,v])=>`<option value="${k}" ${k===Object.keys(regions).find(k=>regions[k]===r)?'selected':''}>${v.name}</option>`).join('')}</select></label><p>Availability is different in each country. Check the regional listing for the current legal services.</p><a class="btn primary watch-main" target="_blank" rel="noopener" href="${justwatch(a)}">Check ${r.name} availability →</a><div class="provider-links">${serviceLinks(a)}</div><div class="legal-note">OtakuStream does not host full episodes. These buttons open external services or availability listings.</div></aside></div>`;document.querySelector('#modal').classList.add('show');document.querySelector('#modal').setAttribute('aria-hidden','false')}
function setRegion(k){localStorage.setItem('otakuRegion',k);const title=document.querySelector('#modalContent h2')?.textContent;const a=shows.find(x=>x.title===title);if(a)openInfo(a.key)}
function setHero(i){heroIndex=(i+shows.length)%shows.length;const a=shows[heroIndex];document.querySelector('#heroArt').style.backgroundImage=`url('${a.banner||a.image||''}')`;document.querySelector('#heroTitle').textContent=a.title;document.querySelector('#heroScore').textContent=a.score;document.querySelector('#heroDesc').textContent=a.desc;document.querySelector('#heroTrailer').onclick=()=>openInfo(a.key);document.querySelector('#heroWatch').onclick=()=>openInfo(a.key);document.querySelector('#heroList').onclick=()=>toggleSaved(a.key);document.querySelector('#heroCarousel').innerHTML=shows.slice(0,4).map((x,n)=>`<div class="hero-pick ${n===heroIndex?'active':''}" onclick="setHero(${n})"><img src="${x.image||''}" alt=""><span>${esc(x.title)}</span></div>`).join('');document.querySelector('#heroDots').innerHTML=shows.slice(0,4).map((x,n)=>`<span class="dot ${n===heroIndex?'active':''}"></span>`).join('')}
async function loadAniList(){const query=`query($search:String!){Media(search:$search,type:ANIME,isAdult:false){title{romaji english}coverImage{extraLarge large}bannerImage trailer{id site thumbnail}}}`;for(const a of shows){try{const res=await fetch('https://graphql.anilist.co',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query,variables:{search:a.search}})});const json=await res.json();const m=json.data?.Media;if(m){a.image=m.coverImage?.extraLarge||m.coverImage?.large||'';a.banner=m.bannerImage||a.image;if(m.trailer?.site==='youtube'&&m.trailer?.id)a.trailerId=m.trailer.id,a.trailerSite='youtube';}}catch(e){console.warn('AniList request failed',a.title,e)}}setHero(0);rows();render()}

document.querySelector('#close').onclick=()=>document.querySelector('#modal').classList.remove('show');document.querySelector('#modal').onclick=e=>{if(e.target.id==='modal')e.currentTarget.classList.remove('show')};document.querySelector('#search').oninput=render;document.querySelector('#topSearch').oninput=e=>{document.querySelector('#search').value=e.target.value;render();document.querySelector('#browse').scrollIntoView({behavior:'smooth'})};document.querySelectorAll('.genre').forEach(b=>b.onclick=()=>setFilter(b.dataset.filter));document.querySelector('#menuBtn').onclick=()=>document.querySelector('#nav').classList.toggle('open');document.querySelector('#prevHero').onclick=()=>setHero(heroIndex-1);document.querySelector('#nextHero').onclick=()=>setHero(heroIndex+1);document.querySelector('#newsletter').onsubmit=e=>{e.preventDefault();e.currentTarget.querySelector('button').textContent='Subscribed ✓'};render();rows();loadAniList();
