const data=[
{id:1,t:"Demon Slayer",anilist:"Demon Slayer",g:["Action","Fantasy","Adventure"],s:"8.6",d:"Tanjiro Kamado sets out on a dangerous journey to find a cure for his sister and confront the forces behind her transformation.",rank:"01"},
{id:2,t:"One Piece",anilist:"One Piece",g:["Action","Adventure","Fantasy"],s:"9.0",d:"Follow Luffy and the Straw Hat crew on a huge adventure filled with friendship, freedom and the search for the legendary treasure.",rank:"02"},
{id:3,t:"Solo Leveling",anilist:"Solo Leveling",g:["Action","Fantasy"],s:"8.8",d:"Sung Jinwoo rises from the weakest hunter into a powerful fighter after gaining a mysterious system.",rank:"03"},
{id:4,t:"Jujutsu Kaisen",anilist:"Jujutsu Kaisen",g:["Action","Supernatural"],s:"8.7",d:"A supernatural action series where sorcerers battle dangerous curses and protect people from the unseen.",rank:"04"},
{id:5,t:"SPY x FAMILY",anilist:"SPY x FAMILY",g:["Comedy","Action"],s:"8.5",d:"A spy, an assassin and a telepath form a fake family while each secretly hides the truth from the others.",rank:"05"},
{id:6,t:"Frieren: Beyond Journey's End",anilist:"Sousou no Frieren",g:["Fantasy","Adventure","Drama"],s:"9.1",d:"A thoughtful fantasy adventure about memories, friendship and understanding people long after the great battle is over.",rank:"06"},
{id:7,t:"My Hero Academia",anilist:"Boku no Hero Academia",g:["Action","Adventure"],s:"8.3",d:"A hero-school story about courage, rivalry, teamwork and learning what it means to become a hero.",rank:"07"},
{id:8,t:"Attack on Titan",anilist:"Shingeki no Kyojin",g:["Action","Drama","Adventure"],s:"9.0",d:"A dramatic survival story built around mystery, difficult choices and a fight for humanity's future.",rank:"08"}
];
const regions={ZA:{name:"South Africa",code:"za"},US:{name:"United States",code:"us"},GB:{name:"United Kingdom",code:"uk"},CA:{name:"Canada",code:"ca"},AU:{name:"Australia",code:"au"}};
let saved=JSON.parse(localStorage.getItem("savedAnime")||"[]"),filter="All";
const grid=document.querySelector("#grid"),savedEl=document.querySelector("#saved"),none=document.querySelector("#none");
function poster(a,compact=false){let img=a.image?`<img src="${a.image}" alt="${a.t} poster" loading="lazy">`:'';return `<div class="${compact?'mini-poster':'poster'}" style="--c1:#3a1d65;--c2:#0b1021">${img}<div class="image-shade"></div><span class="rank">#${a.rank}</span><span class="score">★ ${a.s}</span><div class="poster-copy"><span class="tag">${compact?'TRENDING':'ANIME'}</span>${compact?`<h3>${a.t}</h3><div class="meta">★ ${a.s} · ${a.g[0]}</div>`:''}</div></div>`}
function card(a){let s=saved.includes(a.id);return `<article class="card">${poster(a)}<div class="body"><h3>${a.t}</h3><div class="meta">${a.g.join(" • ")} · ★ ${a.s}</div><p>${a.d}</p><div class="actions"><button class="mini primary" onclick="openInfo(${a.id})">▶ Watch Trailer</button><button class="mini" onclick="toggle(${a.id})">${s?'✓ Saved':'＋ List'}</button></div></div></article>`}
function render(){let q=document.querySelector("#search").value.toLowerCase();let x=data.filter(a=>(filter==="All"||a.g.includes(filter))&&(a.t+" "+a.g.join(" ")).toLowerCase().includes(q));grid.innerHTML=x.map(card).join("")||`<div class="empty" style="grid-column:1/-1"><div>⌕</div><h3>No anime found</h3><p>Try another title or genre.</p></div>`;let y=data.filter(a=>saved.includes(a.id));savedEl.innerHTML=y.map(card).join("");none.style.display=y.length?"none":"block"}
function renderRows(){document.querySelector("#trendingGrid").innerHTML=data.slice(0,6).map(a=>`<button class="mini-poster" onclick="openInfo(${a.id})">${poster(a,true)}<span class="row-title">${a.t}</span><span class="row-score">★ ${a.s}</span><span class="trailer-pill">▶ Trailer</span></button>`).join("");document.querySelector("#topGrid").innerHTML=[...data].sort((a,b)=>Number(b.s)-Number(a.s)).slice(0,6).map(a=>`<button class="mini-poster" onclick="openInfo(${a.id})">${poster(a,true)}<span class="row-title">${a.t}</span><span class="row-score">★ ${a.s}</span><span class="trailer-pill">▶ Trailer</span></button>`).join("");document.querySelector("#recentGrid").innerHTML=[...data].reverse().slice(0,6).map(a=>`<button class="mini-poster" onclick="openInfo(${a.id})">${poster(a,true)}<span class="row-title">${a.t}</span><span class="row-score">★ ${a.s}</span><span class="trailer-pill">▶ Trailer</span></button>`).join("")}
function toggle(id){saved=saved.includes(id)?saved.filter(x=>x!==id):[...saved,id];localStorage.setItem("savedAnime",JSON.stringify(saved));render()}
function setFilter(v){filter=v;document.querySelectorAll(".genre").forEach(x=>x.classList.toggle("active",x.dataset.filter===v));render();document.querySelector("#browse").scrollIntoView({behavior:"smooth"})}
function trailerEmbed(a){return a.trailerSite==="youtube"&&a.trailerId?`<div class="video-wrap"><iframe src="https://www.youtube-nocookie.com/embed/${a.trailerId}?rel=0" title="${a.t} official trailer" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></div>`:`<div class="video-fallback"><div>▶</div><p>Trailer video not available for embedding yet.</p><a class="btn primary" target="_blank" rel="noopener" href="https://www.youtube.com/results?search_query=${encodeURIComponent(a.t+' official trailer')}">Open Official Trailer Search →</a></div>`}
function justWatch(a,region){return `https://www.justwatch.com/${region.code}/search?q=${encodeURIComponent(a.t)}`}
function providerLinks(a,region){let q=encodeURIComponent(a.t);let links=[['Crunchyroll',`https://www.crunchyroll.com/search?q=${q}`],['Netflix',`https://www.netflix.com/search?q=${q}`],['Prime Video',`https://www.primevideo.com/search/ref=atv_nb_sr?phrase=${q}`]];return links.map(([n,u])=>`<a class="watch-link" target="_blank" rel="noopener" href="${u}">${n} ↗</a>`).join('')}
function openInfo(id){let a=data.find(x=>x.id===id),region=regions[localStorage.getItem('region')||'ZA'];document.querySelector("#modalContent").innerHTML=`<div class="preview-layout"><div><div class="eyebrow">OFFICIAL TRAILER</div><h2>${a.t}</h2><p><b>★ ${a.s}/10</b> · ${a.g.join(' · ')}</p>${trailerEmbed(a)}</div><div class="watch-panel"><h3>Where to Watch</h3><label class="region-label">Your region<select id="regionSelect" onchange="changeRegion(this.value)">${Object.entries(regions).map(([k,r])=>`<option value="${k}" ${k===(localStorage.getItem('region')||'ZA')?'selected':''}>${r.name}</option>`).join('')}</select></label><p>Availability changes by country. Check the region-aware listing before choosing a service.</p><a class="btn primary full" target="_blank" rel="noopener" href="${justWatch(a,region)}">Check legal options in ${region.name} →</a><div class="provider-grid">${providerLinks(a,region)}</div><small>OtakuStream does not host full episodes. Streaming links lead to external services.</small></div></div>`;document.querySelector("#modal").classList.add("show");document.querySelector("#modal").setAttribute("aria-hidden","false")}
function changeRegion(code){localStorage.setItem('region',code);const openId=data.find(a=>document.querySelector('#modalContent h2')?.textContent===a.t)?.id;if(openId)openInfo(openId)}
async function loadAniList(){const query=`query($title:String!){Media(search:$title,type:ANIME){id title{romaji english native} coverImage{large extraLarge} bannerImage trailer{id site thumbnail} }}`;for(const a of data){try{let r=await fetch('https://graphql.anilist.co',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query,variables:{title:a.anilist}})});let j=await r.json(),m=j.data?.Media;if(m){a.image=m.coverImage?.extraLarge||m.coverImage?.large||'';a.banner=m.bannerImage||a.image;if(m.trailer?.site==='youtube'&&m.trailer?.id){a.trailerSite='youtube';a.trailerId=m.trailer.id}}}catch(e){console.warn('Anime image/trailer lookup failed',a.t,e)} }
const featured=data[0];if(featured.banner)document.querySelector('#heroBg').style.backgroundImage=`linear-gradient(90deg,#05050beF 0%,#080817bb 45%,#08081735 100%),url('${featured.banner}')`;render();renderRows()}

document.querySelector('#close').onclick=()=>{document.querySelector('#modal').classList.remove('show');document.querySelector('#modal').setAttribute('aria-hidden','true')};document.querySelector('#modal').onclick=e=>{if(e.target.id==='modal')e.currentTarget.classList.remove('show')};
document.querySelector('#search').oninput=render;document.querySelector('#topSearch').oninput=e=>{document.querySelector('#search').value=e.target.value;render();document.querySelector('#browse').scrollIntoView({behavior:'smooth'})};
document.querySelectorAll('.genre').forEach(b=>b.onclick=()=>setFilter(b.dataset.filter));document.querySelector('#menu').onclick=()=>document.querySelector('#nav').classList.toggle('open');document.querySelectorAll('#nav a').forEach(a=>a.onclick=()=>document.querySelector('#nav').classList.remove('open'));
render();renderRows();loadAniList();
